USE PokemonDB;
INSERT INTO user (username, password, name, surname, timestamp)
VALUES
    ('mario.rossi', SHA2('mario.rossi',256), 'Mario', 'Rossi', '2023-02-12 12:00:00'),
    ('luca.bianchi', SHA2('luca.bianchi',256), 'Luca', 'Bianchi', '2023-02-12 12:15:00'),
    ('giovanni.verdi', SHA2('giovanni.verdi',256), 'Giovanni', 'Verdi', '2023-02-12 12:30:00'),
    ('paola.neri', SHA2('paola.neri',256), 'Paola', 'Neri', '2023-02-12 12:45:00'),
    ('andrea.rossi', SHA2('andrea.rossi',256), 'Andrea', 'Rossi', '2023-02-12 13:00:00'),
    ('elena.bianchi', SHA2('elena.bianchi',256), 'Elena', 'Bianchi', '2023-02-12 13:15:00'),
    ('marco.verdi', SHA2('marco.verdi',256), 'Marco', 'Verdi', '2023-02-12 13:30:00'),
    ('silvia.neri', SHA2('silvia.neri',256), 'Silvia', 'Neri', '2023-02-12 13:45:00'),
    ('simone.rossi', SHA2('simone.rossi',256), 'Simone', 'Rossi', '2023-02-12 14:00:00'),
    ('francesca.bianchi', SHA2('francesca.bianchi',256), 'Francesca', 'Bianchi', '2023-02-12 14:15:00'),
    ('gianluca.verdi', SHA2('gianluca.verdi',256), 'Gianluca', 'Verdi', '2023-02-12 14:30:00'),
    ('ilaria.neri', SHA2('ilaria.neri',256), 'Ilaria', 'Neri', '2023-02-12 14:45:00'),
    ('fabio.rossi', SHA2('fabio.rossi',256), 'Fabio', 'Rossi', '2023-02-12 15:00:00'),
    ('serena.bianchi', SHA2('serena.bianchi',256), 'Serena', 'Bianchi', '2023-02-12 15:15:00'),
    ('alessandro.verdi', SHA2('alessandro.verdi',256), 'Alessandro', 'Verdi', '2023-02-12 15:30:00'),
    ('valentina.neri', SHA2('valentina.neri',256), 'Valentina', 'Neri', '2023-02-12 15:45:00'),
    ('davide.rossi', SHA2('davide.rossi',256), 'Davide', 'Rossi', '2023-02-12 16:00:00'),
    ('elisa.bianchi', SHA2('elisa.bianchi',256), 'Elisa', 'Bianchi', '2023-02-12 16:15:00'),
    ('maria.verdi', SHA2('maria.verdi',256), 'Maria', 'Verdi', '2023-02-12 16:30:00'),
    ('giuseppe.neri', SHA2('giuseppe.neri',256), 'Giuseppe', 'Neri', '2023-02-12 16:45:00');

INSERT INTO pokemon (pokemonName,imageUrl , primaryType, secondaryType , attack , defense)
VALUES
    ('Bulbasaur','https://static.wikia.nocookie.net/pokemongo/images/4/43/Bulbasaur.png','Grass','Seed',118,111),
    ('Ivysaur','https://static.wikia.nocookie.net/pokemongo/images/8/86/Ivysaur.png','Grass','Seed',151,143),
    ('Venusaur','https://static.wikia.nocookie.net/pokemongo/images/b/be/Venusaur.png','Grass','Seed',198,189),
    ('Charmander','https://static.wikia.nocookie.net/pokemongo/images/5/56/Charmander.png','Fire','Lizard',116,93),
    ('Charmeleon','https://static.wikia.nocookie.net/pokemongo/images/f/fb/Charmeleon.png','Fire','Flame',158,126),
    ('Charizard','https://static.wikia.nocookie.net/pokemongo/images/9/95/Charizard.png','Fire','Flame',223,173),
    ('Squirtle','https://static.wikia.nocookie.net/pokemongo/images/e/e3/Squirtle.png','Water','Tiny',94,121),
    ('Wartortle','https://static.wikia.nocookie.net/pokemongo/images/d/d7/Wartortle.png','Water','Turtle',126,155),
    ('Blastoise','https://static.wikia.nocookie.net/pokemongo/images/4/41/Blastoise.png','Water','Shellfish',171,207),
    ('Caterpie', 'https://static.wikia.nocookie.net/pokemongo/images/0/05/Caterpie.png', 'Bug', 'Worm', 55, 55),
    ('Metapod', 'https://static.wikia.nocookie.net/pokemongo/images/6/6b/Metapod.png', 'Bug', 'Cocoon', 45, 80),
    ('Butterfree', 'https://static.wikia.nocookie.net/pokemongo/images/9/96/Butterfree.png', 'Bug', 'Butterfly', 167, 137),
    ('Weedle', 'https://static.wikia.nocookie.net/pokemongo/images/d/d6/Weedle.png', 'Bug', 'Hairy', 63, 50),
    ('Kakuna', 'https://static.wikia.nocookie.net/pokemongo/images/6/63/Kakuna.png', 'Bug', 'Cocoon', 46, 75),
    ('Beedrill', 'https://static.wikia.nocookie.net/pokemongo/images/0/0d/Beedrill.png', 'Bug', 'Poison', 169, 130),
    ('Pidgey', 'https://static.wikia.nocookie.net/pokemongo/images/b/b7/Pidgey.png', 'Normal', 'Tiny', 85, 73),
    ('Pidgeotto', 'https://static.wikia.nocookie.net/pokemongo/images/5/57/Pidgeotto.png', 'Normal', 'Bird', 117, 105),
    ('Pidgeot', 'https://static.wikia.nocookie.net/pokemongo/images/a/a9/Pidgeot.png', 'Normal', 'Bird', 166, 154),
    ('Rattata', 'https://static.wikia.nocookie.net/pokemongo/images/c/c4/Rattata.png', 'Normal', 'Mouse', 103, 70),
    ('Raticate', 'https://static.wikia.nocookie.net/pokemongo/images/d/d6/Raticate.png', 'Normal', 'Mouse', 161, 139),
    ('Spearow', 'https://static.wikia.nocookie.net/pokemongo/images/a/a1/Spearow.png', 'Normal', 'Tiny', 112, 60),
    ('Fearow', 'https://static.wikia.nocookie.net/pokemongo/images/4/41/Fearow.png', 'Normal', 'Beak', 182, 133),
    ('Ekans', 'https://static.wikia.nocookie.net/pokemongo/images/1/11/Ekans.png', 'Poison', 'Snake', 110, 97),
    ('Arbok', 'https://static.wikia.nocookie.net/pokemongo/images/4/4d/Arbok.png', 'Poison', 'Cobra', 167, 153),
    ('Pikachu', 'https://static.wikia.nocookie.net/pokemongo/images/7/77/Pikachu.png', 'Electric', 'Mouse', 112, 96),
    ('Raichu', 'https://static.wikia.nocookie.net/pokemongo/images/3/34/Raichu.png', 'Electric', 'Mouse', 193, 151),
    ('Sandshrew', 'https://static.wikia.nocookie.net/pokemongo/images/d/df/Sandshrew.png', 'Ground', 'Mouse', 126, 120),
    ('Sandslash', 'https://static.wikia.nocookie.net/pokemongo/images/1/13/Sandslash.png', 'Ground', 'Mouse', 182, 175),
    ('Nidoran?', 'https://static.wikia.nocookie.net/pokemongo/images/c/c8/Nidoran%E2%99%80.png', 'Poison', 'Poison', 86, 89),
    ('Nidorina', 'https://static.wikia.nocookie.net/pokemongo/images/3/31/Nidorina.png', 'Poison', 'Poison', 117, 120),
    ('Nidoqueen', 'https://static.wikia.nocookie.net/pokemongo/images/4/43/Nidoqueen.png', 'Poison', 'Drill', 180, 173),
    ('Nidoran?', 'https://static.wikia.nocookie.net/pokemongo/images/6/60/Nidoran%E2%99%82.png', 'Poison', 'Poison', 105, 76),
    ('Nidorino', 'https://static.wikia.nocookie.net/pokemongo/images/7/7a/Nidorino.png', 'Poison', 'Poison', 137, 111),
    ('Nidoking', 'https://static.wikia.nocookie.net/pokemongo/images/7/76/Nidoking.png', 'Poison', 'Drill', 204, 156),
    ('Clefairy', 'https://static.wikia.nocookie.net/pokemongo/images/d/d2/Clefairy.png', 'Fairy', 'Fairy', 107, 108),
    ('Clefable', 'https://static.wikia.nocookie.net/pokemongo/images/d/d5/Clefable.png', 'Fairy', 'Fairy', 178, 162),
    ('Vulpix', 'https://static.wikia.nocookie.net/pokemongo/images/8/8d/Vulpix.png', 'Fire', 'Fox', 96, 109),
    ('Ninetales', 'https://static.wikia.nocookie.net/pokemongo/images/9/98/Ninetales.png', 'Fire', 'Fox', 169, 190),
    ('Jigglypuff', 'https://static.wikia.nocookie.net/pokemongo/images/a/af/Jigglypuff.png', 'Normal', 'Balloon', 80, 41),
    ('Wigglytuff', 'https://static.wikia.nocookie.net/pokemongo/images/f/f1/Wigglytuff.png', 'Normal', 'Balloon', 156, 90),
    ('Zubat', 'https://static.wikia.nocookie.net/pokemongo/images/6/67/Zubat.png', 'Poison', 'Bat', 83, 73),
    ('Golbat', 'https://static.wikia.nocookie.net/pokemongo/images/2/2c/Golbat.png', 'Poison', 'Bat', 161, 150),
    ('Oddish', 'https://static.wikia.nocookie.net/pokemongo/images/d/d9/Oddish.png', 'Grass', 'Weed', 131, 112),
    ('Gloom', 'https://static.wikia.nocookie.net/pokemongo/images/5/59/Gloom.png', 'Grass', 'Weed', 153, 136),
    ('Vileplume', 'https://static.wikia.nocookie.net/pokemongo/images/3/32/Vileplume.png', 'Grass', 'Flower', 202, 167),
    ('Paras', 'https://static.wikia.nocookie.net/pokemongo/images/e/ee/Paras.png', 'Bug', 'Mushroom', 121, 99),
    ('Parasect', 'https://static.wikia.nocookie.net/pokemongo/images/6/62/Parasect.png', 'Bug', 'Mushroom', 165, 146),
    ('Venonat', 'https://static.wikia.nocookie.net/pokemongo/images/d/d3/Venonat.png', 'Bug', 'Insect', 100, 100),
    ('Venomoth', 'https://static.wikia.nocookie.net/pokemongo/images/c/c2/Venomoth.png', 'Bug', 'Poison', 179, 143),
    ('Diglett', 'https://static.wikia.nocookie.net/pokemongo/images/7/7a/Diglett.png', 'Ground', 'Mole', 109, 78),
    ('Dugtrio', 'https://static.wikia.nocookie.net/pokemongo/images/8/8b/Dugtrio.png', 'Ground', 'Mole', 167, 134),
    ('Meowth', 'https://static.wikia.nocookie.net/pokemongo/images/9/99/Meowth.png', 'Normal', 'Scratch', 92, 78),
    ('Persian', 'https://static.wikia.nocookie.net/pokemongo/images/b/b3/Persian.png', 'Normal', 'Classy', 150, 136),
    ('Psyduck', 'https://static.wikia.nocookie.net/pokemongo/images/3/32/Psyduck.png', 'Water', 'Duck', 122, 95),
    ('Golduck', 'https://static.wikia.nocookie.net/pokemongo/images/c/cf/Golduck.png', 'Water', 'Duck', 191, 162),
    ('Mankey', 'https://static.wikia.nocookie.net/pokemongo/images/8/8b/Mankey.png', 'Fighting', 'Pig', 148, 82),
    ('Primeape', 'https://static.wikia.nocookie.net/pokemongo/images/e/e0/Primeape.png', 'Fighting', 'Pig', 207, 138),
    ('Growlithe', 'https://static.wikia.nocookie.net/pokemongo/images/b/bb/Growlithe.png', 'Fire', 'Puppy', 136, 93),
    ('Arcanine', 'https://static.wikia.nocookie.net/pokemongo/images/5/50/Arcanine.png', 'Fire', 'Legendary', 227, 166),
    ('Poliwag', 'https://static.wikia.nocookie.net/pokemongo/images/9/90/Poliwag.png', 'Water', 'Tadpole', 101, 82),
    ('Poliwhirl', 'https://static.wikia.nocookie.net/pokemongo/images/2/24/Poliwhirl.png', 'Water', 'Tadpole', 130, 123),
    ('Poliwrath', 'https://static.wikia.nocookie.net/pokemongo/images/8/85/Poliwrath.png', 'Water', 'Tadpole', 182, 184),
    ('Abra', 'https://static.wikia.nocookie.net/pokemongo/images/f/f6/Abra.png', 'Psychic', 'Psi', 195, 82),
    ('Kadabra', 'https://static.wikia.nocookie.net/pokemongo/images/b/b0/Kadabra.png', 'Psychic', 'Psi', 232, 117),
    ('Alakazam', 'https://static.wikia.nocookie.net/pokemongo/images/f/f5/Alakazam.png', 'Psychic', 'Psi', 271, 167),
    ('Machop', 'https://static.wikia.nocookie.net/pokemongo/images/2/2b/Machop.png', 'Fighting', 'Superpower', 137, 82),
    ('Machoke', 'https://static.wikia.nocookie.net/pokemongo/images/c/ca/Machoke.png', 'Fighting', 'Superpower', 177, 125),
    ('Machamp', 'https://static.wikia.nocookie.net/pokemongo/images/b/bf/Machamp.png', 'Fighting', 'Superpower', 234, 159),
    ('Bellsprout', 'https://static.wikia.nocookie.net/pokemongo/images/d/d1/Bellsprout.png', 'Grass', 'Flower', 139, 61),
    ('Weepinbell', 'https://static.wikia.nocookie.net/pokemongo/images/f/f9/Weepinbell.png', 'Grass', 'Flycatcher', 172, 92),
    ('Victreebel', 'https://static.wikia.nocookie.net/pokemongo/images/5/55/Victreebel.png', 'Grass', 'Flycatcher', 207, 135),
    ('Tentacool', 'https://static.wikia.nocookie.net/pokemongo/images/4/43/Tentacool.png', 'Water', 'Jellyfish', 97, 149),
    ('Tentacruel', 'https://static.wikia.nocookie.net/pokemongo/images/7/78/Tentacruel.png', 'Water', 'Jellyfish', 166, 209),
    ('Geodude', 'https://static.wikia.nocookie.net/pokemongo/images/1/12/Geodude.png', 'Rock', 'Rock', 132, 132),
    ('Graveler', 'https://static.wikia.nocookie.net/pokemongo/images/b/b6/Graveler.png', 'Rock', 'Rock', 164, 164),
    ('Golem', 'https://static.wikia.nocookie.net/pokemongo/images/c/ce/Golem.png', 'Rock', 'Megaton', 211, 198),
    ('Ponyta', 'https://static.wikia.nocookie.net/pokemongo/images/5/5f/Ponyta.png', 'Fire', 'Fire', 170, 127),
    ('Rapidash', 'https://static.wikia.nocookie.net/pokemongo/images/0/01/Rapidash.png', 'Fire', 'Fire', 207, 162),
    ('Slowpoke', 'https://static.wikia.nocookie.net/pokemongo/images/9/9b/Slowpoke.png', 'Water', 'Dopey', 109, 98),
    ('Slowbro', 'https://static.wikia.nocookie.net/pokemongo/images/e/e1/Slowbro.png', 'Water', 'Hermit', 177, 180),
    ('Magnemite', 'https://static.wikia.nocookie.net/pokemongo/images/8/80/Magnemite.png', 'Electric', 'Magnet', 165, 121),
    ('Magneton', 'https://static.wikia.nocookie.net/pokemongo/images/d/d1/Magneton.png', 'Electric', 'Magnet', 223, 169),
    ('Farfetch', 'https://static.wikia.nocookie.net/pokemongo/images/b/b5/Farfetch%27d.png', 'Normal', 'Wild', 124, 115),
    ('Doduo', 'https://static.wikia.nocookie.net/pokemongo/images/9/9c/Doduo.png', 'Normal', 'Twin', 158, 83),
    ('Dodrio', 'https://static.wikia.nocookie.net/pokemongo/images/1/1a/Dodrio.png', 'Normal', 'Triple', 218, 140),
    ('Seel', 'https://static.wikia.nocookie.net/pokemongo/images/f/f1/Seel.png', 'Water', 'Sea', 85, 121),
    ('Dewgong', 'https://static.wikia.nocookie.net/pokemongo/images/1/1d/Dewgong.png', 'Water', 'Sea', 139, 177),
    ('Grimer', 'https://static.wikia.nocookie.net/pokemongo/images/d/d7/Grimer.png', 'Poison', 'Sludge', 135, 90),
    ('Muk', 'https://static.wikia.nocookie.net/pokemongo/images/8/8e/Muk.png', 'Poison', 'Sludge', 190, 172),
    ('Shellder', 'https://static.wikia.nocookie.net/pokemongo/images/6/63/Shellder.png', 'Water', 'Bivalve', 116, 134),
    ('Cloyster', 'https://static.wikia.nocookie.net/pokemongo/images/7/71/Cloyster.png', 'Water', 'Bivalve', 186, 256),
    ('Gastly', 'https://static.wikia.nocookie.net/pokemongo/images/c/c1/Gastly.png', 'Ghost', 'Gas', 186, 67),
    ('Haunter', 'https://static.wikia.nocookie.net/pokemongo/images/4/41/Haunter.png', 'Ghost', 'Gas', 223, 107),
    ('Gengar', 'https://static.wikia.nocookie.net/pokemongo/images/f/f8/Gengar.png', 'Ghost', 'Shadow', 261, 149),
    ('Onix', 'https://static.wikia.nocookie.net/pokemongo/images/b/b2/Onix.png', 'Rock', 'Rock', 85, 232),
    ('Drowzee', 'https://static.wikia.nocookie.net/pokemongo/images/5/5d/Drowzee.png', 'Psychic', 'Hypnosis', 89, 136),
    ('Hypno', 'https://static.wikia.nocookie.net/pokemongo/images/0/0e/Hypno.png', 'Psychic', 'Hypnosis', 144, 193),
    ('Krabby', 'https://static.wikia.nocookie.net/pokemongo/images/d/da/Krabby.png', 'Water', 'River', 181, 124),
    ('Kingler', 'https://static.wikia.nocookie.net/pokemongo/images/a/a4/Kingler.png', 'Water', 'Pincer', 240, 181),
    ('Voltorb', 'https://static.wikia.nocookie.net/pokemongo/images/8/80/Voltorb.png', 'Electric', 'Ball', 109, 111),
    ('Electrode', 'https://static.wikia.nocookie.net/pokemongo/images/5/52/Electrode.png', 'Electric', 'Ball', 173, 173),
    ('Exeggcute', 'https://static.wikia.nocookie.net/pokemongo/images/5/5f/Exeggcute.png', 'Grass', 'Egg', 107, 125),
    ('Exeggutor', 'https://static.wikia.nocookie.net/pokemongo/images/e/e0/Exeggutor.png', 'Grass', 'Coconut', 233, 149),
    ('Cubone', 'https://static.wikia.nocookie.net/pokemongo/images/6/65/Cubone.png', 'Ground', 'Lonely', 90, 144),
    ('Marowak', 'https://static.wikia.nocookie.net/pokemongo/images/c/c4/Marowak.png', 'Ground', 'Bone', 144, 186),
    ('Hitmonlee', 'https://static.wikia.nocookie.net/pokemongo/images/0/0f/Hitmonlee.png', 'Fighting', 'Kicking', 224, 181),
    ('Hitmonchan', 'https://static.wikia.nocookie.net/pokemongo/images/7/73/Hitmonchan.png', 'Fighting', 'Punching', 193, 197),
    ('Lickitung', 'https://static.wikia.nocookie.net/pokemongo/images/a/ab/Lickitung.png', 'Normal', 'Licking', 108, 137),
    ('Koffing', 'https://static.wikia.nocookie.net/pokemongo/images/b/b2/Koffing.png', 'Poison', 'Poison', 119, 141),
    ('Weezing', 'https://static.wikia.nocookie.net/pokemongo/images/8/88/Weezing.png', 'Poison', 'Poison', 174, 197),
    ('Rhyhorn', 'https://static.wikia.nocookie.net/pokemongo/images/3/36/Rhyhorn.png', 'Ground', 'Spikes', 140, 127),
    ('Rhydon', 'https://static.wikia.nocookie.net/pokemongo/images/0/01/Rhydon.png', 'Ground', 'Drill', 222, 171),
    ('Chansey', 'https://static.wikia.nocookie.net/pokemongo/images/2/2b/Chansey.png', 'Normal', 'Egg', 60, 128),
    ('Tangela', 'https://static.wikia.nocookie.net/pokemongo/images/0/03/Tangela.png', 'Grass', 'Vine', 183, 169),
    ('Kangaskhan', 'https://static.wikia.nocookie.net/pokemongo/images/3/39/Kangaskhan.png', 'Normal', 'Parent', 181, 165),
    ('Horsea', 'https://static.wikia.nocookie.net/pokemongo/images/6/6c/Horsea.png', 'Water', 'Dragon', 129, 103),
    ('Seadra', 'https://static.wikia.nocookie.net/pokemongo/images/2/2d/Seadra.png', 'Water', 'Dragon', 187, 156),
    ('Goldeen', 'https://static.wikia.nocookie.net/pokemongo/images/9/99/Goldeen.png', 'Water', 'Goldfish', 123, 110),
    ('Seaking', 'https://static.wikia.nocookie.net/pokemongo/images/8/8b/Seaking.png', 'Water', 'Goldfish', 175, 147),
    ('Staryu', 'https://static.wikia.nocookie.net/pokemongo/images/e/e8/Staryu.png', 'Water', 'Star', 137, 112),
    ('Starmie', 'https://static.wikia.nocookie.net/pokemongo/images/5/56/Starmie.png', 'Water', 'Mysterious', 210, 184),
    ('Mr. Mime', 'https://static.wikia.nocookie.net/pokemongo/images/4/4f/Mr._Mime.png', 'Psychic', 'Barrier', 192, 205),
    ('Scyther', 'https://static.wikia.nocookie.net/pokemongo/images/c/c2/Scyther.png', 'Bug', 'Mantis', 218, 170),
    ('Jynx', 'https://static.wikia.nocookie.net/pokemongo/images/e/e2/Jynx.png', 'Ice', 'Human', 223, 151),
    ('Electabuzz', 'https://static.wikia.nocookie.net/pokemongo/images/3/3a/Electabuzz.png', 'Electric', 'Electric', 198, 158),
    ('Magmar', 'https://static.wikia.nocookie.net/pokemongo/images/4/46/Magmar.png', 'Fire', 'Spitfire', 206, 154),
    ('Pinsir', 'https://static.wikia.nocookie.net/pokemongo/images/b/b4/Pinsir.png', 'Bug', 'Stag', 238, 182),
    ('Tauros', 'https://static.wikia.nocookie.net/pokemongo/images/9/98/Tauros.png', 'Normal', 'Wild', 198, 183),
    ('Magikarp', 'https://static.wikia.nocookie.net/pokemongo/images/0/01/Magikarp.png', 'Water', 'Fish', 29, 85),
    ('Gyarados', 'https://static.wikia.nocookie.net/pokemongo/images/d/d7/Gyarados.png', 'Water', 'Atrocious', 237, 186),
    ('Lapras', 'https://static.wikia.nocookie.net/pokemongo/images/3/30/Lapras.png', 'Water', 'Transport', 165, 174),
    ('Ditto', 'https://static.wikia.nocookie.net/pokemongo/images/0/03/Ditto.png', 'Normal', 'Transform', 91, 91),
    ('Eevee', 'https://static.wikia.nocookie.net/pokemongo/images/f/f2/Eevee.png', 'Normal', 'Evolution', 104, 114),
    ('Vaporeon', 'https://static.wikia.nocookie.net/pokemongo/images/f/fc/Vaporeon.png', 'Water', 'Bubble', 205, 161),
    ('Jolteon', 'https://static.wikia.nocookie.net/pokemongo/images/1/1e/Jolteon.png', 'Electric', 'Lightning', 232, 182),
    ('Flareon', 'https://static.wikia.nocookie.net/pokemongo/images/1/17/Flareon.png', 'Fire', 'Flame', 246, 179),
    ('Porygon', 'https://static.wikia.nocookie.net/pokemongo/images/2/2d/Porygon.png', 'Normal', 'Virtual', 153, 136),
    ('Omanyte', 'https://static.wikia.nocookie.net/pokemongo/images/a/a4/Omanyte.png', 'Rock', 'Spiral', 155, 153),
    ('Omastar', 'https://static.wikia.nocookie.net/pokemongo/images/9/97/Omastar.png', 'Rock', 'Spiral', 207, 201),
    ('Kabuto', 'https://static.wikia.nocookie.net/pokemongo/images/a/a1/Kabuto.png', 'Rock', 'Shellfish', 148, 140),
    ('Kabutops', 'https://static.wikia.nocookie.net/pokemongo/images/7/72/Kabutops.png', 'Rock', 'Shellfish', 220, 186),
    ('Aerodactyl', 'https://static.wikia.nocookie.net/pokemongo/images/e/e6/Aerodactyl.png', 'Rock', 'Fossil', 221, 159),
    ('Snorlax', 'https://static.wikia.nocookie.net/pokemongo/images/0/0b/Snorlax.png', 'Normal', 'Sleeping', 190, 169),
    ('Articuno', 'https://static.wikia.nocookie.net/pokemongo/images/5/52/Articuno.png', 'Ice', 'Freeze', 192, 236),
    ('Zapdos', 'https://static.wikia.nocookie.net/pokemongo/images/d/d8/Zapdos.png', 'Electric', 'Electric', 253, 185),
    ('Moltres', 'https://static.wikia.nocookie.net/pokemongo/images/0/01/Moltres.png', 'Fire', 'Flame', 251, 181),
    ('Dratini', 'https://static.wikia.nocookie.net/pokemongo/images/9/99/Dratini.png', 'Dragon', 'Dragon', 119, 91),
    ('Dragonair', 'https://static.wikia.nocookie.net/pokemongo/images/5/5a/Dragonair.png', 'Dragon', 'Dragon', 163, 135),
    ('Dragonite', 'https://static.wikia.nocookie.net/pokemongo/images/a/a6/Dragonite.png', 'Dragon', 'Dragon', 263, 198),
    ('Mewtwo', 'https://static.wikia.nocookie.net/pokemongo/images/d/d3/Mewtwo.png', 'Psychic', 'Genetic', 300, 182),
    ('Mew', 'https://static.wikia.nocookie.net/pokemongo/images/b/bf/Mew.png', 'Psychic', 'New', 210, 210),
    ('Chikorita', 'https://static.wikia.nocookie.net/pokemongo/images/4/4e/Chikorita.png', 'Grass', 'Leaf', 92, 122),
    ('Bayleef', 'https://static.wikia.nocookie.net/pokemongo/images/1/1b/Bayleef.png', 'Grass', 'Leaf', 122, 155),
    ('Meganium', 'https://static.wikia.nocookie.net/pokemongo/images/4/40/Meganium.png', 'Grass', 'Herb', 168, 202),
    ('Cyndaquil', 'https://static.wikia.nocookie.net/pokemongo/images/9/99/Cyndaquil.png', 'Fire', 'Fire', 116, 93),
    ('Quilava', 'https://static.wikia.nocookie.net/pokemongo/images/4/4a/Quilava.png', 'Fire', 'Volcano', 158, 126),
    ('Typhlosion', 'https://static.wikia.nocookie.net/pokemongo/images/5/51/Typhlosion.png', 'Fire', 'Volcano', 223, 173),
    ('Totodile', 'https://static.wikia.nocookie.net/pokemongo/images/e/e7/Totodile.png', 'Water', 'Big', 117, 109),
    ('Croconaw', 'https://static.wikia.nocookie.net/pokemongo/images/d/d7/Croconaw.png', 'Water', 'Big', 150, 142),
    ('Feraligatr', 'https://static.wikia.nocookie.net/pokemongo/images/5/51/Feraligatr.png', 'Water', 'Big', 205, 188),
    ('Sentret', 'https://static.wikia.nocookie.net/pokemongo/images/5/5c/Sentret.png', 'Normal', 'Scout', 79, 73),
    ('Furret', 'https://static.wikia.nocookie.net/pokemongo/images/d/de/Furret.png', 'Normal', 'Long', 148, 125),
    ('Hoothoot', 'https://static.wikia.nocookie.net/pokemongo/images/d/d3/Hoothoot.png', 'Normal', 'Owl', 67, 88),
    ('Noctowl', 'https://static.wikia.nocookie.net/pokemongo/images/3/37/Noctowl.png', 'Normal', 'Owl', 145, 156),
    ('Ledyba', 'https://static.wikia.nocookie.net/pokemongo/images/a/a8/Ledyba.png', 'Bug', 'Five', 72, 118),
    ('Ledian', 'https://static.wikia.nocookie.net/pokemongo/images/e/ee/Ledian.png', 'Bug', 'Five', 107, 179),
    ('Spinarak', 'https://static.wikia.nocookie.net/pokemongo/images/a/aa/Spinarak.png', 'Bug', 'String', 105, 73),
    ('Ariados', 'https://static.wikia.nocookie.net/pokemongo/images/2/29/Ariados.png', 'Bug', 'Long', 161, 124),
    ('Crobat', 'https://static.wikia.nocookie.net/pokemongo/images/4/4d/Crobat.png', 'Poison', 'Bat', 194, 178),
    ('Chinchou', 'https://static.wikia.nocookie.net/pokemongo/images/b/b1/Chinchou.png', 'Water', 'Angler', 106, 97),
    ('Lanturn', 'https://static.wikia.nocookie.net/pokemongo/images/1/16/Lanturn.png', 'Water', 'Light', 146, 137),
    ('Pichu', 'https://static.wikia.nocookie.net/pokemongo/images/9/9d/Pichu.png', 'Electric', 'Tiny', 77, 53),
    ('Cleffa', 'https://static.wikia.nocookie.net/pokemongo/images/a/a7/Cleffa.png', 'Fairy', 'Star', 75, 79),
    ('Igglybuff', 'https://static.wikia.nocookie.net/pokemongo/images/5/5b/Igglybuff.png', 'Normal', 'Balloon', 69, 32),
    ('Togepi', 'https://static.wikia.nocookie.net/pokemongo/images/f/ff/Togepi.png', 'Fairy', 'Spike', 67, 116),
    ('Togetic', 'https://static.wikia.nocookie.net/pokemongo/images/a/a7/Togetic.png', 'Fairy', 'Happiness', 139, 181),
    ('Natu', 'https://static.wikia.nocookie.net/pokemongo/images/6/69/Natu.png', 'Psychic', 'Tiny', 134, 89),
    ('Xatu', 'https://static.wikia.nocookie.net/pokemongo/images/e/e0/Xatu.png', 'Psychic', 'Mystic', 192, 146),
    ('Mareep', 'https://static.wikia.nocookie.net/pokemongo/images/d/da/Mareep.png', 'Electric', 'Wool', 114, 79),
    ('Flaaffy', 'https://static.wikia.nocookie.net/pokemongo/images/e/ed/Flaaffy.png', 'Electric', 'Wool', 145, 109),
    ('Ampharos', 'https://static.wikia.nocookie.net/pokemongo/images/f/f5/Ampharos.png', 'Electric', 'Light', 211, 169),
    ('Bellossom', 'https://static.wikia.nocookie.net/pokemongo/images/e/ed/Bellossom.png', 'Grass', 'Flower', 169, 186),
    ('Marill', 'https://static.wikia.nocookie.net/pokemongo/images/5/55/Marill.png', 'Water', 'Aqua', 37, 93),
    ('Azumarill', 'https://static.wikia.nocookie.net/pokemongo/images/1/1a/Azumarill.png', 'Water', 'Aqua', 112, 152),
    ('Sudowoodo', 'https://static.wikia.nocookie.net/pokemongo/images/1/13/Sudowoodo.png', 'Rock', 'Imitation', 167, 176),
    ('Politoed', 'https://static.wikia.nocookie.net/pokemongo/images/f/fd/Politoed.png', 'Water', 'Frog', 174, 179),
    ('Hoppip', 'https://static.wikia.nocookie.net/pokemongo/images/9/90/Hoppip.png', 'Grass', 'Cottonweed', 67, 94),
    ('Skiploom', 'https://static.wikia.nocookie.net/pokemongo/images/f/f1/Skiploom.png', 'Grass', 'Cottonweed', 91, 120),
    ('Jumpluff', 'https://static.wikia.nocookie.net/pokemongo/images/4/43/Jumpluff.png', 'Grass', 'Cottonweed', 118, 183),
    ('Aipom', 'https://static.wikia.nocookie.net/pokemongo/images/b/bd/Aipom.png', 'Normal', 'Long', 136, 112),
    ('Sunkern', 'https://static.wikia.nocookie.net/pokemongo/images/d/de/Sunkern.png', 'Grass', 'Seed', 55, 55),
    ('Sunflora', 'https://static.wikia.nocookie.net/pokemongo/images/7/70/Sunflora.png', 'Grass', 'Sun', 185, 135),
    ('Yanma', 'https://static.wikia.nocookie.net/pokemongo/images/c/c4/Yanma.png', 'Bug', 'Clear', 154, 94),
    ('Wooper', 'https://static.wikia.nocookie.net/pokemongo/images/4/42/Wooper.png', 'Water', 'Water', 75, 66),
    ('Quagsire', 'https://static.wikia.nocookie.net/pokemongo/images/1/1b/Quagsire.png', 'Water', 'Water', 152, 143),
    ('Espeon', 'https://static.wikia.nocookie.net/pokemongo/images/e/ef/Espeon.png', 'Psychic', 'Sun', 261, 175),
    ('Umbreon', 'https://static.wikia.nocookie.net/pokemongo/images/9/9f/Umbreon.png', 'Dark', 'Moonlight', 126, 240),
    ('Murkrow', 'https://static.wikia.nocookie.net/pokemongo/images/5/5c/Murkrow.png', 'Dark', 'Darkness', 175, 87),
    ('Slowking', 'https://static.wikia.nocookie.net/pokemongo/images/c/c5/Slowking.png', 'Water', 'Royal', 177, 180),
    ('Misdreavus', 'https://static.wikia.nocookie.net/pokemongo/images/6/6c/Misdreavus.png', 'Ghost', 'Screech', 167, 154),
    ('Unown', 'https://static.wikia.nocookie.net/pokemongo/images/f/f1/Unown.png', 'Psychic', 'Symbol', 136, 91),
    ('Wobbuffet', 'https://static.wikia.nocookie.net/pokemongo/images/c/cf/Wobbuffet.png', 'Psychic', 'Patient', 60, 106),
    ('Girafarig', 'https://static.wikia.nocookie.net/pokemongo/images/e/eb/Girafarig.png', 'Normal', 'Long', 182, 133),
    ('Pineco', 'https://static.wikia.nocookie.net/pokemongo/images/d/da/Pineco.png', 'Bug', 'Bagworm', 108, 122),
    ('Forretress', 'https://static.wikia.nocookie.net/pokemongo/images/d/d6/Forretress.png', 'Bug', 'Bagworm', 161, 205),
    ('Dunsparce', 'https://static.wikia.nocookie.net/pokemongo/images/5/50/Dunsparce.png', 'Normal', 'Land', 131, 128),
    ('Gligar', 'https://static.wikia.nocookie.net/pokemongo/images/2/20/Gligar.png', 'Ground', 'Fly', 143, 184),
    ('Steelix', 'https://static.wikia.nocookie.net/pokemongo/images/2/2a/Steelix.png', 'Steel', 'Iron', 148, 272),
    ('Snubbull', 'https://static.wikia.nocookie.net/pokemongo/images/2/23/Snubbull.png', 'Fairy', 'Fairy', 137, 85),
    ('Granbull', 'https://static.wikia.nocookie.net/pokemongo/images/2/28/Granbull.png', 'Fairy', 'Fairy', 212, 131),
    ('Qwilfish', 'https://static.wikia.nocookie.net/pokemongo/images/c/c1/Qwilfish.png', 'Water', 'Balloon', 184, 138),
    ('Scizor', 'https://static.wikia.nocookie.net/pokemongo/images/8/87/Scizor.png', 'Bug', 'Pincer', 236, 181),
    ('Shuckle', 'https://static.wikia.nocookie.net/pokemongo/images/3/3c/Shuckle.png', 'Bug', 'Mold', 17, 396),
    ('Heracross', 'https://static.wikia.nocookie.net/pokemongo/images/2/21/Heracross.png', 'Bug', 'Single', 234, 179),
    ('Sneasel', 'https://static.wikia.nocookie.net/pokemongo/images/4/47/Sneasel.png', 'Dark', 'Sharp', 189, 146),
    ('Teddiursa', 'https://static.wikia.nocookie.net/pokemongo/images/1/1e/Teddiursa.png', 'Normal', 'Little', 142, 93),
    ('Ursaring', 'https://static.wikia.nocookie.net/pokemongo/images/6/61/Ursaring.png', 'Normal', 'Hibernator', 236, 144),
    ('Slugma', 'https://static.wikia.nocookie.net/pokemongo/images/0/06/Slugma.png', 'Fire', 'Lava', 118, 71),
    ('Magcargo', 'https://static.wikia.nocookie.net/pokemongo/images/8/8f/Magcargo.png', 'Fire', 'Lava', 139, 191),
    ('Swinub', 'https://static.wikia.nocookie.net/pokemongo/images/3/38/Swinub.png', 'Ice', 'Pig', 90, 69),
    ('Piloswine', 'https://static.wikia.nocookie.net/pokemongo/images/3/38/Piloswine.png', 'Ice', 'Swine', 181, 138),
    ('Corsola', 'https://static.wikia.nocookie.net/pokemongo/images/6/6a/Corsola.png', 'Water', 'Coral', 118, 156),
    ('Remoraid', 'https://static.wikia.nocookie.net/pokemongo/images/b/ba/Remoraid.png', 'Water', 'Jet', 127, 69),
    ('Octillery', 'https://static.wikia.nocookie.net/pokemongo/images/7/7a/Octillery.png', 'Water', 'Jet', 197, 141),
    ('Delibird', 'https://static.wikia.nocookie.net/pokemongo/images/4/4f/Delibird.png', 'Ice', 'Delivery', 128, 90),
    ('Mantine', 'https://static.wikia.nocookie.net/pokemongo/images/9/99/Mantine.png', 'Water', 'Kite', 148, 226),
    ('Skarmory', 'https://static.wikia.nocookie.net/pokemongo/images/d/d1/Skarmory.png', 'Steel', 'Armor', 148, 226),
    ('Houndour', 'https://static.wikia.nocookie.net/pokemongo/images/b/ba/Houndour.png', 'Dark', 'Dark', 152, 83),
    ('Houndoom', 'https://static.wikia.nocookie.net/pokemongo/images/3/3f/Houndoom.png', 'Dark', 'Dark', 224, 144),
    ('Kingdra', 'https://static.wikia.nocookie.net/pokemongo/images/b/bd/Kingdra.png', 'Water', 'Dragon', 194, 194),
    ('Phanpy', 'https://static.wikia.nocookie.net/pokemongo/images/9/9f/Phanpy.png', 'Ground', 'Long', 107, 98),
    ('Donphan', 'https://static.wikia.nocookie.net/pokemongo/images/6/68/Donphan.png', 'Ground', 'Armor', 214, 185),
    ('Porygon2', 'https://static.wikia.nocookie.net/pokemongo/images/b/b0/Porygon2.png', 'Normal', 'Virtual', 198, 180),
    ('Stantler', 'https://static.wikia.nocookie.net/pokemongo/images/5/5a/Stantler.png', 'Normal', 'Big', 192, 131),
    ('Smeargle', 'https://static.wikia.nocookie.net/pokemongo/images/a/a9/Smeargle.png', 'Normal', 'Painter', 40, 83),
    ('Tyrogue', 'https://static.wikia.nocookie.net/pokemongo/images/b/b0/Tyrogue.png', 'Fighting', 'Scuffle', 64, 64),
    ('Hitmontop', 'https://static.wikia.nocookie.net/pokemongo/images/a/a2/Hitmontop.png', 'Fighting', 'Handstand', 173, 207),
    ('Smoochum', 'https://static.wikia.nocookie.net/pokemongo/images/c/ce/Smoochum.png', 'Ice', 'Kiss', 153, 91),
    ('Elekid', 'https://static.wikia.nocookie.net/pokemongo/images/a/a6/Elekid.png', 'Electric', 'Electric', 135, 101),
    ('Magby', 'https://static.wikia.nocookie.net/pokemongo/images/4/42/Magby.png', 'Fire', 'Live', 151, 99),
    ('Miltank', 'https://static.wikia.nocookie.net/pokemongo/images/b/b9/Miltank.png', 'Normal', 'Milk', 157, 193),
    ('Blissey', 'https://static.wikia.nocookie.net/pokemongo/images/2/2a/Blissey.png', 'Normal', 'Happiness', 129, 169),
    ('Raikou', 'https://static.wikia.nocookie.net/pokemongo/images/d/d6/Raikou.png', 'Electric', 'Thunder', 241, 195),
    ('Entei', 'https://static.wikia.nocookie.net/pokemongo/images/0/0a/Entei.png', 'Fire', 'Volcano', 235, 171),
    ('Suicune', 'https://static.wikia.nocookie.net/pokemongo/images/c/c3/Suicune.png', 'Water', 'Aurora', 180, 235),
    ('Larvitar', 'https://static.wikia.nocookie.net/pokemongo/images/7/71/Larvitar.png', 'Rock', 'Rock', 115, 93),
    ('Pupitar', 'https://static.wikia.nocookie.net/pokemongo/images/5/58/Pupitar.png', 'Rock', 'Hard', 155, 133),
    ('Tyranitar', 'https://static.wikia.nocookie.net/pokemongo/images/9/95/Tyranitar.png', 'Rock', 'Armor', 251, 207),
    ('Lugia', 'https://static.wikia.nocookie.net/pokemongo/images/a/a7/Lugia.png', 'Psychic', 'Diving', 193, 310),
    ('Ho-Oh', 'https://static.wikia.nocookie.net/pokemongo/images/0/00/Ho-Oh.png', 'Fire', 'Rainbow', 239, 244),
    ('Celebi', 'https://static.wikia.nocookie.net/pokemongo/images/e/e4/Celebi.png', 'Psychic', 'Time', 210, 210),
    ('Treecko', 'https://static.wikia.nocookie.net/pokemongo/images/b/b8/Treecko.png', 'Grass', 'Wood', 124, 94),
    ('Grovyle', 'https://static.wikia.nocookie.net/pokemongo/images/6/6a/Grovyle.png', 'Grass', 'Wood', 172, 120),
    ('Sceptile', 'https://static.wikia.nocookie.net/pokemongo/images/7/79/Sceptile.png', 'Grass', 'Forest', 223, 169),
    ('Torchic', 'https://static.wikia.nocookie.net/pokemongo/images/4/4f/Torchic.png', 'Fire', 'Chick', 130, 87),
    ('Combusken', 'https://static.wikia.nocookie.net/pokemongo/images/c/cf/Combusken.png', 'Fire', 'Young', 163, 115),
    ('Blaziken', 'https://static.wikia.nocookie.net/pokemongo/images/a/ab/Blaziken.png', 'Fire', 'Blaze', 240, 141),
    ('Mudkip', 'https://static.wikia.nocookie.net/pokemongo/images/a/ae/Mudkip.png', 'Water', 'Mud', 126, 93),
    ('Marshtomp', 'https://static.wikia.nocookie.net/pokemongo/images/d/d7/Marshtomp.png', 'Water', 'Mud', 156, 133),
    ('Swampert', 'https://static.wikia.nocookie.net/pokemongo/images/d/d7/Swampert.png', 'Water', 'Mud', 208, 175),
    ('Poochyena', 'https://static.wikia.nocookie.net/pokemongo/images/d/d4/Poochyena.png', 'Dark', 'Bite', 96, 61),
    ('Mightyena', 'https://static.wikia.nocookie.net/pokemongo/images/7/7c/Mightyena.png', 'Dark', 'Bite', 171, 132),
    ('Zigzagoon', 'https://static.wikia.nocookie.net/pokemongo/images/a/a7/Zigzagoon.png', 'Normal', 'Tiny', 58, 80),
    ('Linoone', 'https://static.wikia.nocookie.net/pokemongo/images/b/b5/Linoone.png', 'Normal', 'Rushing', 142, 128),
    ('Wurmple', 'https://static.wikia.nocookie.net/pokemongo/images/5/52/Wurmple.png', 'Bug', 'Worm', 75, 59),
    ('Silcoon', 'https://static.wikia.nocookie.net/pokemongo/images/5/50/Silcoon.png', 'Bug', 'Cocoon', 60, 77),
    ('Beautifly', 'https://static.wikia.nocookie.net/pokemongo/images/a/ae/Beautifly.png', 'Bug', 'Butterfly', 189, 98),
    ('Cascoon', 'https://static.wikia.nocookie.net/pokemongo/images/7/7c/Cascoon.png', 'Bug', 'Cocoon', 60, 77),
    ('Dustox', 'https://static.wikia.nocookie.net/pokemongo/images/1/12/Dustox.png', 'Bug', 'Poison', 98, 162),
    ('Lotad', 'https://static.wikia.nocookie.net/pokemongo/images/3/3c/Lotad.png', 'Water', 'Water', 71, 77),
    ('Lombre', 'https://static.wikia.nocookie.net/pokemongo/images/d/d8/Lombre.png', 'Water', 'Jolly', 112, 119),
    ('Ludicolo', 'https://static.wikia.nocookie.net/pokemongo/images/6/69/Ludicolo.png', 'Water', 'Carefree', 173, 176),
    ('Seedot', 'https://static.wikia.nocookie.net/pokemongo/images/7/7e/Seedot.png', 'Grass', 'Acorn', 71, 77),
    ('Nuzleaf', 'https://static.wikia.nocookie.net/pokemongo/images/4/4b/Nuzleaf.png', 'Grass', 'Wily', 134, 78),
    ('Shiftry', 'https://static.wikia.nocookie.net/pokemongo/images/9/99/Shiftry.png', 'Grass', 'Wicked', 200, 121),
    ('Taillow', 'https://static.wikia.nocookie.net/pokemongo/images/a/a3/Taillow.png', 'Normal', 'Tiny', 106, 61),
    ('Swellow', 'https://static.wikia.nocookie.net/pokemongo/images/7/71/Swellow.png', 'Normal', 'Swallow', 185, 124),
    ('Wingull', 'https://static.wikia.nocookie.net/pokemongo/images/f/ff/Wingull.png', 'Water', 'Seagull', 106, 61),
    ('Pelipper', 'https://static.wikia.nocookie.net/pokemongo/images/8/8a/Pelipper.png', 'Water', 'Water', 175, 174),
    ('Ralts', 'https://static.wikia.nocookie.net/pokemongo/images/e/e8/Ralts.png', 'Psychic', 'Feeling', 79, 59),
    ('Kirlia', 'https://static.wikia.nocookie.net/pokemongo/images/2/25/Kirlia.png', 'Psychic', 'Emotion', 117, 90),
    ('Gardevoir', 'https://static.wikia.nocookie.net/pokemongo/images/2/28/Gardevoir.png', 'Psychic', 'Embrace', 237, 195),
    ('Surskit', 'https://static.wikia.nocookie.net/pokemongo/images/9/9f/Surskit.png', 'Bug', 'Pond', 93, 87),
    ('Masquerain', 'https://static.wikia.nocookie.net/pokemongo/images/4/43/Masquerain.png', 'Bug', 'Eyeball', 192, 150),
    ('Shroomish', 'https://static.wikia.nocookie.net/pokemongo/images/4/45/Shroomish.png', 'Grass', 'Mushroom', 74, 110),
    ('Breloom', 'https://static.wikia.nocookie.net/pokemongo/images/3/39/Breloom.png', 'Grass', 'Mushroom', 241, 144),
    ('Slakoth', 'https://static.wikia.nocookie.net/pokemongo/images/e/e3/Slakoth.png', 'Normal', 'Slacker', 104, 92),
    ('Vigoroth', 'https://static.wikia.nocookie.net/pokemongo/images/6/6d/Vigoroth.png', 'Normal', 'Wild', 159, 145),
    ('Slaking', 'https://static.wikia.nocookie.net/pokemongo/images/1/1c/Slaking.png', 'Normal', 'Lazy', 290, 166),
    ('Nincada', 'https://static.wikia.nocookie.net/pokemongo/images/8/8e/Nincada.png', 'Bug', 'Trainee', 80, 126),
    ('Ninjask', 'https://static.wikia.nocookie.net/pokemongo/images/d/d1/Ninjask.png', 'Bug', 'Ninja', 199, 112),
    ('Shedinja', 'https://static.wikia.nocookie.net/pokemongo/images/f/f4/Shedinja.png', 'Bug', 'Shed', 153, 73),
    ('Whismur', 'https://static.wikia.nocookie.net/pokemongo/images/f/f4/Whismur.png', 'Normal', 'Whisper', 92, 42),
    ('Loudred', 'https://static.wikia.nocookie.net/pokemongo/images/1/1e/Loudred.png', 'Normal', 'Big', 134, 81),
    ('Exploud', 'https://static.wikia.nocookie.net/pokemongo/images/2/21/Exploud.png', 'Normal', 'Loud', 179, 137),
    ('Makuhita', 'https://static.wikia.nocookie.net/pokemongo/images/d/d1/Makuhita.png', 'Fighting', 'Guts', 99, 54),
    ('Hariyama', 'https://static.wikia.nocookie.net/pokemongo/images/c/cb/Hariyama.png', 'Fighting', 'Arm', 209, 114),
    ('Azurill', 'https://static.wikia.nocookie.net/pokemongo/images/c/ca/Azurill.png', 'Normal', 'Polka', 36, 71),
    ('Nosepass', 'https://static.wikia.nocookie.net/pokemongo/images/5/52/Nosepass.png', 'Rock', 'Compass', 82, 215),
    ('Skitty', 'https://static.wikia.nocookie.net/pokemongo/images/f/f0/Skitty.png', 'Normal', 'Kitten', 84, 79),
    ('Delcatty', 'https://static.wikia.nocookie.net/pokemongo/images/3/3e/Delcatty.png', 'Normal', 'Prim', 132, 127),
    ('Sableye', 'https://static.wikia.nocookie.net/pokemongo/images/9/99/Sableye.png', 'Dark', 'Darkness', 141, 136),
    ('Mawile', 'https://static.wikia.nocookie.net/pokemongo/images/b/bd/Mawile.png', 'Steel', 'Deceiver', 155, 141),
    ('Aron', 'https://static.wikia.nocookie.net/pokemongo/images/3/30/Aron.png', 'Steel', 'Iron', 121, 141),
    ('Lairon', 'https://static.wikia.nocookie.net/pokemongo/images/a/a4/Lairon.png', 'Steel', 'Iron', 158, 198),
    ('Aggron', 'https://static.wikia.nocookie.net/pokemongo/images/1/1e/Aggron.png', 'Steel', 'Iron', 198, 257),
    ('Meditite', 'https://static.wikia.nocookie.net/pokemongo/images/2/28/Meditite.png', 'Fighting', 'Meditate', 78, 107),
    ('Medicham', 'https://static.wikia.nocookie.net/pokemongo/images/b/be/Medicham.png', 'Fighting', 'Meditate', 121, 152),
    ('Electrike', 'https://static.wikia.nocookie.net/pokemongo/images/0/07/Electrike.png', 'Electric', 'Lightning', 123, 78),
    ('Manectric', 'https://static.wikia.nocookie.net/pokemongo/images/3/37/Manectric.png', 'Electric', 'Discharge', 215, 127),
    ('Plusle', 'https://static.wikia.nocookie.net/pokemongo/images/b/b0/Plusle.png', 'Electric', 'Cheering', 167, 129),
    ('Minun', 'https://static.wikia.nocookie.net/pokemongo/images/f/f5/Minun.png', 'Electric', 'Cheering', 147, 150),
    ('Volbeat', 'https://static.wikia.nocookie.net/pokemongo/images/3/3a/Volbeat.png', 'Bug', 'Firefly', 143, 166),
    ('Illumise', 'https://static.wikia.nocookie.net/pokemongo/images/e/ea/Illumise.png', 'Bug', 'Firefly', 143, 166),
    ('Roselia', 'https://static.wikia.nocookie.net/pokemongo/images/f/f9/Roselia.png', 'Grass', 'Thorn', 186, 131),
    ('Gulpin', 'https://static.wikia.nocookie.net/pokemongo/images/3/31/Gulpin.png', 'Poison', 'Stomach', 80, 99),
    ('Swalot', 'https://static.wikia.nocookie.net/pokemongo/images/4/48/Swalot.png', 'Poison', 'Poison', 140, 159),
    ('Carvanha', 'https://static.wikia.nocookie.net/pokemongo/images/f/fe/Carvanha.png', 'Water', 'Savage', 171, 39),
    ('Sharpedo', 'https://static.wikia.nocookie.net/pokemongo/images/b/b0/Sharpedo.png', 'Water', 'Brutal', 243, 83),
    ('Wailmer', 'https://static.wikia.nocookie.net/pokemongo/images/3/30/Wailmer.png', 'Water', 'Ball', 136, 68),
    ('Wailord', 'https://static.wikia.nocookie.net/pokemongo/images/8/89/Wailord.png', 'Water', 'Float', 175, 87),
    ('Numel', 'https://static.wikia.nocookie.net/pokemongo/images/1/10/Numel.png', 'Fire', 'Numb', 119, 79),
    ('Camerupt', 'https://static.wikia.nocookie.net/pokemongo/images/a/a6/Camerupt.png', 'Fire', 'Eruption', 194, 136),
    ('Torkoal', 'https://static.wikia.nocookie.net/pokemongo/images/6/63/Torkoal.png', 'Fire', 'Coal', 151, 203),
    ('Spoink', 'https://static.wikia.nocookie.net/pokemongo/images/8/85/Spoink.png', 'Psychic', 'Bounce', 125, 122),
    ('Grumpig', 'https://static.wikia.nocookie.net/pokemongo/images/4/46/Grumpig.png', 'Psychic', 'Manipulate', 171, 188),
    ('Spinda', 'https://static.wikia.nocookie.net/pokemongo/images/3/3b/Spinda.png', 'Normal', 'Spot', 116, 116),
    ('Trapinch', 'https://static.wikia.nocookie.net/pokemongo/images/e/e7/Trapinch.png', 'Ground', 'Ant', 162, 78),
    ('Vibrava', 'https://static.wikia.nocookie.net/pokemongo/images/1/13/Vibrava.png', 'Ground', 'Vibration', 134, 99),
    ('Flygon', 'https://static.wikia.nocookie.net/pokemongo/images/7/72/Flygon.png', 'Ground', 'Mystic', 205, 168),
    ('Cacnea', 'https://static.wikia.nocookie.net/pokemongo/images/1/14/Cacnea.png', 'Grass', 'Cactus', 156, 74),
    ('Cacturne', 'https://static.wikia.nocookie.net/pokemongo/images/e/ec/Cacturne.png', 'Grass', 'Scarecrow', 221, 115),
    ('Swablu', 'https://static.wikia.nocookie.net/pokemongo/images/2/2b/Swablu.png', 'Normal', 'Cotton', 76, 132),
    ('Altaria', 'https://static.wikia.nocookie.net/pokemongo/images/2/24/Altaria.png', 'Dragon', 'Humming', 141, 201),
    ('Zangoose', 'https://static.wikia.nocookie.net/pokemongo/images/b/b3/Zangoose.png', 'Normal', 'Cat', 222, 124),
    ('Seviper', 'https://static.wikia.nocookie.net/pokemongo/images/7/7e/Seviper.png', 'Poison', 'Fang', 196, 118),
    ('Lunatone', 'https://static.wikia.nocookie.net/pokemongo/images/9/99/Lunatone.png', 'Rock', 'Meteorite', 178, 153),
    ('Solrock', 'https://static.wikia.nocookie.net/pokemongo/images/5/5f/Solrock.png', 'Rock', 'Meteorite', 178, 153),
    ('Barboach', 'https://static.wikia.nocookie.net/pokemongo/images/f/f3/Barboach.png', 'Water', 'Whiskers', 93, 82),
    ('Whiscash', 'https://static.wikia.nocookie.net/pokemongo/images/9/9a/Whiscash.png', 'Water', 'Whiskers', 151, 141),
    ('Corphish', 'https://static.wikia.nocookie.net/pokemongo/images/5/56/Corphish.png', 'Water', 'Ruffian', 141, 99),
    ('Crawdaunt', 'https://static.wikia.nocookie.net/pokemongo/images/e/ed/Crawdaunt.png', 'Water', 'Rogue', 224, 142),
    ('Baltoy', 'https://static.wikia.nocookie.net/pokemongo/images/f/fa/Baltoy.png', 'Ground', 'Clay', 77, 124),
    ('Claydol', 'https://static.wikia.nocookie.net/pokemongo/images/e/ec/Claydol.png', 'Ground', 'Clay', 140, 229),
    ('Lileep', 'https://static.wikia.nocookie.net/pokemongo/images/6/6e/Lileep.png', 'Rock', 'Sea', 105, 150),
    ('Cradily', 'https://static.wikia.nocookie.net/pokemongo/images/2/2b/Cradily.png', 'Rock', 'Barnacle', 152, 194),
    ('Anorith', 'https://static.wikia.nocookie.net/pokemongo/images/e/e6/Anorith.png', 'Rock', 'Old', 176, 100),
    ('Armaldo', 'https://static.wikia.nocookie.net/pokemongo/images/7/7b/Armaldo.png', 'Rock', 'Plate', 222, 174),
    ('Feebas', 'https://static.wikia.nocookie.net/pokemongo/images/2/25/Feebas.png', 'Water', 'Fish', 29, 85),
    ('Milotic', 'https://static.wikia.nocookie.net/pokemongo/images/b/b1/Milotic.png', 'Water', 'Tender', 192, 219),
    ('Castform', 'https://static.wikia.nocookie.net/pokemongo/images/d/df/Castform.png', 'Normal', 'Weather', 139, 139),
    ('Kecleon', 'https://static.wikia.nocookie.net/pokemongo/images/8/85/Kecleon.png', 'Normal', 'Color', 161, 189),
    ('Shuppet', 'https://static.wikia.nocookie.net/pokemongo/images/e/e5/Shuppet.png', 'Ghost', 'Puppet', 138, 65),
    ('Banette', 'https://static.wikia.nocookie.net/pokemongo/images/1/10/Banette.png', 'Ghost', 'Marionette', 218, 126),
    ('Duskull', 'https://static.wikia.nocookie.net/pokemongo/images/1/1b/Duskull.png', 'Ghost', 'Requiem', 70, 162),
    ('Dusclops', 'https://static.wikia.nocookie.net/pokemongo/images/4/49/Dusclops.png', 'Ghost', 'Beckon', 124, 234),
    ('Tropius', 'https://static.wikia.nocookie.net/pokemongo/images/c/cd/Tropius.png', 'Grass', 'Fruit', 136, 163),
    ('Chimecho', 'https://static.wikia.nocookie.net/pokemongo/images/2/29/Chimecho.png', 'Psychic', 'Wind', 175, 170),
    ('Absol', 'https://static.wikia.nocookie.net/pokemongo/images/7/7d/Absol.png', 'Dark', 'Disaster', 246, 120),
    ('Wynaut', 'https://static.wikia.nocookie.net/pokemongo/images/a/a0/Wynaut.png', 'Psychic', 'Bright', 41, 86),
    ('Snorunt', 'https://static.wikia.nocookie.net/pokemongo/images/2/2d/Snorunt.png', 'Ice', 'Snow', 95, 95),
    ('Glalie', 'https://static.wikia.nocookie.net/pokemongo/images/0/07/Glalie.png', 'Ice', 'Face', 162, 162),
    ('Spheal', 'https://static.wikia.nocookie.net/pokemongo/images/f/fe/Spheal.png', 'Ice', 'Clap', 95, 90),
    ('Sealeo', 'https://static.wikia.nocookie.net/pokemongo/images/9/99/Sealeo.png', 'Ice', 'Ball', 137, 132),
    ('Walrein', 'https://static.wikia.nocookie.net/pokemongo/images/8/80/Walrein.png', 'Ice', 'Ice', 182, 176),
    ('Clamperl', 'https://static.wikia.nocookie.net/pokemongo/images/c/ce/Clamperl.png', 'Water', 'Bivalve', 133, 135),
    ('Huntail', 'https://static.wikia.nocookie.net/pokemongo/images/4/49/Huntail.png', 'Water', 'Deep', 197, 179),
    ('Gorebyss', 'https://static.wikia.nocookie.net/pokemongo/images/4/41/Gorebyss.png', 'Water', 'South', 211, 179),
    ('Relicanth', 'https://static.wikia.nocookie.net/pokemongo/images/a/a1/Relicanth.png', 'Water', 'Longevity', 162, 203),
    ('Luvdisc', 'https://static.wikia.nocookie.net/pokemongo/images/c/ce/Luvdisc.png', 'Water', 'Rendezvous', 81, 128),
    ('Bagon', 'https://static.wikia.nocookie.net/pokemongo/images/9/9d/Bagon.png', 'Dragon', 'Rock', 134, 93),
    ('Shelgon', 'https://static.wikia.nocookie.net/pokemongo/images/4/48/Shelgon.png', 'Dragon', 'Endurance', 172, 155),
    ('Salamence', 'https://static.wikia.nocookie.net/pokemongo/images/f/fe/Salamence.png', 'Dragon', 'Dragon', 277, 168),
    ('Beldum', 'https://static.wikia.nocookie.net/pokemongo/images/f/f5/Beldum.png', 'Steel', 'Iron', 96, 132),
    ('Metang', 'https://static.wikia.nocookie.net/pokemongo/images/f/fb/Metang.png', 'Steel', 'Iron', 138, 176),
    ('Metagross', 'https://static.wikia.nocookie.net/pokemongo/images/9/95/Metagross.png', 'Steel', 'Iron', 257, 228),
    ('Regirock', 'https://static.wikia.nocookie.net/pokemongo/images/b/bd/Regirock.png', 'Rock', 'Rock', 179, 309),
    ('Regice', 'https://static.wikia.nocookie.net/pokemongo/images/f/ff/Regice.png', 'Ice', 'Iceberg', 179, 309),
    ('Registeel', 'https://static.wikia.nocookie.net/pokemongo/images/b/b7/Registeel.png', 'Steel', 'Iron', 143, 285),
    ('Latias', 'https://static.wikia.nocookie.net/pokemongo/images/2/28/Latias.png', 'Dragon', 'Eon', 228, 246),
    ('Latios', 'https://static.wikia.nocookie.net/pokemongo/images/6/6f/Latios.png', 'Dragon', 'Eon', 268, 212),
    ('Kyogre', 'https://static.wikia.nocookie.net/pokemongo/images/f/f3/Kyogre.png', 'Water', 'Sea', 270, 228),
    ('Groudon', 'https://static.wikia.nocookie.net/pokemongo/images/d/d5/Groudon.png', 'Ground', 'Continent', 270, 228),
    ('Rayquaza', 'https://static.wikia.nocookie.net/pokemongo/images/6/66/Rayquaza.png', 'Dragon', 'Sky', 284, 170),
    ('Jirachi', 'https://static.wikia.nocookie.net/pokemongo/images/6/60/Jirachi.png', 'Steel', 'Wish', 210, 210),
    ('Deoxys', 'https://static.wikia.nocookie.net/pokemongo/images/d/d5/Deoxys.png', 'Psychic', 'DNA', 345, 115),
    ('Turtwig', 'https://static.wikia.nocookie.net/pokemongo/images/c/c8/Turtwig.png', 'Grass', 'Tiny', 119, 110),
    ('Grotle', 'https://static.wikia.nocookie.net/pokemongo/images/7/75/Grotle.png', 'Grass', 'Grove', 157, 143),
    ('Torterra', 'https://static.wikia.nocookie.net/pokemongo/images/0/05/Torterra.png', 'Grass', 'Continent', 202, 188),
    ('Chimchar', 'https://static.wikia.nocookie.net/pokemongo/images/9/9f/Chimchar.png', 'Fire', 'Chimp', 113, 86),
    ('Monferno', 'https://static.wikia.nocookie.net/pokemongo/images/6/64/Monferno.png', 'Fire', 'Playful', 158, 105),
    ('Infernape', 'https://static.wikia.nocookie.net/pokemongo/images/1/17/Infernape.png', 'Fire', 'Flame', 222, 151),
    ('Piplup', 'https://static.wikia.nocookie.net/pokemongo/images/1/11/Piplup.png', 'Water', 'Penguin', 112, 102),
    ('Prinplup', 'https://static.wikia.nocookie.net/pokemongo/images/1/1b/Prinplup.png', 'Water', 'Penguin', 150, 139),
    ('Empoleon', 'https://static.wikia.nocookie.net/pokemongo/images/b/bb/Empoleon.png', 'Water', 'Emperor', 210, 186),
    ('Starly', 'https://static.wikia.nocookie.net/pokemongo/images/0/08/Starly.png', 'Normal', 'Starling', 101, 58),
    ('Staravia', 'https://static.wikia.nocookie.net/pokemongo/images/d/df/Staravia.png', 'Normal', 'Starling', 142, 94),
    ('Staraptor', 'https://static.wikia.nocookie.net/pokemongo/images/1/1f/Staraptor.png', 'Normal', 'Predator', 234, 140),
    ('Bidoof', 'https://static.wikia.nocookie.net/pokemongo/images/b/b9/Bidoof.png', 'Normal', 'Plump', 80, 73),
    ('Bibarel', 'https://static.wikia.nocookie.net/pokemongo/images/1/1a/Bibarel.png', 'Normal', 'Beaver', 162, 119),
    ('Kricketot', 'https://static.wikia.nocookie.net/pokemongo/images/d/df/Kricketot.png', 'Bug', 'Cricket', 45, 74),
    ('Kricketune', 'https://static.wikia.nocookie.net/pokemongo/images/c/cf/Kricketune.png', 'Bug', 'Cricket', 160, 100),
    ('Shinx', 'https://static.wikia.nocookie.net/pokemongo/images/a/a5/Shinx.png', 'Electric', 'Flash', 117, 64),
    ('Luxio', 'https://static.wikia.nocookie.net/pokemongo/images/5/51/Luxio.png', 'Electric', 'Spark', 159, 95),
    ('Luxray', 'https://static.wikia.nocookie.net/pokemongo/images/e/ee/Luxray.png', 'Electric', 'Gleam', 232, 156),
    ('Budew', 'https://static.wikia.nocookie.net/pokemongo/images/5/5d/Budew.png', 'Grass', 'Bud', 91, 109),
    ('Roserade', 'https://static.wikia.nocookie.net/pokemongo/images/8/82/Roserade.png', 'Grass', 'Bouquet', 243, 185),
    ('Cranidos', 'https://static.wikia.nocookie.net/pokemongo/images/a/ac/Cranidos.png', 'Rock', 'Head', 218, 71),
    ('Rampardos', 'https://static.wikia.nocookie.net/pokemongo/images/9/97/Rampardos.png', 'Rock', 'Head', 295, 109),
    ('Shieldon', 'https://static.wikia.nocookie.net/pokemongo/images/5/57/Shieldon.png', 'Rock', 'Shield', 76, 195),
    ('Bastiodon', 'https://static.wikia.nocookie.net/pokemongo/images/f/f4/Bastiodon.png', 'Rock', 'Shield', 94, 286),
    ('Burmy', 'https://static.wikia.nocookie.net/pokemongo/images/9/9e/Burmy.png', 'Bug', 'Bagworm', 53, 83),
    ('Wormadam', 'https://static.wikia.nocookie.net/pokemongo/images/4/4b/Wormadam.png', 'Bug', 'Bagworm', 141, 180),
    ('Mothim', 'https://static.wikia.nocookie.net/pokemongo/images/b/bd/Mothim.png', 'Bug', 'Moth', 185, 98),
    ('Combee', 'https://static.wikia.nocookie.net/pokemongo/images/6/6e/Combee.png', 'Bug', 'Tiny', 59, 83),
    ('Vespiquen', 'https://static.wikia.nocookie.net/pokemongo/images/5/52/Vespiquen.png', 'Bug', 'Beehive', 149, 190),
    ('Pachirisu', 'https://static.wikia.nocookie.net/pokemongo/images/f/f9/Pachirisu.png', 'Electric', 'EleSquirrel', 94, 172),
    ('Buizel', 'https://static.wikia.nocookie.net/pokemongo/images/b/ba/Buizel.png', 'Water', 'Sea', 132, 67),
    ('Floatzel', 'https://static.wikia.nocookie.net/pokemongo/images/b/b9/Floatzel.png', 'Water', 'Sea', 221, 114),
    ('Cherubi', 'https://static.wikia.nocookie.net/pokemongo/images/7/74/Cherubi.png', 'Grass', 'Cherry', 108, 92),
    ('Cherrim', 'https://static.wikia.nocookie.net/pokemongo/images/b/ba/Cherrim.png', 'Grass', 'Blossom', 170, 153),
    ('Shellos', 'https://static.wikia.nocookie.net/pokemongo/images/b/b2/Shellos.png', 'Water', 'Sea', 103, 105),
    ('Gastrodon', 'https://static.wikia.nocookie.net/pokemongo/images/3/3f/Gastrodon.png', 'Water', 'Sea', 169, 143),
    ('Ambipom', 'https://static.wikia.nocookie.net/pokemongo/images/5/56/Ambipom.png', 'Normal', 'Long', 205, 143),
    ('Drifloon', 'https://static.wikia.nocookie.net/pokemongo/images/2/29/Drifloon.png', 'Ghost', 'Balloon', 117, 80),
    ('Drifblim', 'https://static.wikia.nocookie.net/pokemongo/images/6/63/Drifblim.png', 'Ghost', 'Blimp', 180, 102),
    ('Buneary', 'https://static.wikia.nocookie.net/pokemongo/images/6/6e/Buneary.png', 'Normal', 'Rabbit', 130, 105),
    ('Lopunny', 'https://static.wikia.nocookie.net/pokemongo/images/0/06/Lopunny.png', 'Normal', 'Rabbit', 156, 194),
    ('Mismagius', 'https://static.wikia.nocookie.net/pokemongo/images/2/25/Mismagius.png', 'Ghost', 'Magical', 211, 187),
    ('Honchkrow', 'https://static.wikia.nocookie.net/pokemongo/images/d/d3/Honchkrow.png', 'Dark', 'Big', 243, 103),
    ('Glameow', 'https://static.wikia.nocookie.net/pokemongo/images/0/08/Glameow.png', 'Normal', 'Catty', 109, 82),
    ('Purugly', 'https://static.wikia.nocookie.net/pokemongo/images/5/51/Purugly.png', 'Normal', 'Tiger', 172, 133),
    ('Chingling', 'https://static.wikia.nocookie.net/pokemongo/images/0/0c/Chingling.png', 'Psychic', 'Bell', 114, 94),
    ('Stunky', 'https://static.wikia.nocookie.net/pokemongo/images/7/75/Stunky.png', 'Poison', 'Skunk', 121, 90),
    ('Skuntank', 'https://static.wikia.nocookie.net/pokemongo/images/5/5a/Skuntank.png', 'Poison', 'Skunk', 184, 132),
    ('Bronzor', 'https://static.wikia.nocookie.net/pokemongo/images/1/19/Bronzor.png', 'Steel', 'Bronze', 43, 154),
    ('Bronzong', 'https://static.wikia.nocookie.net/pokemongo/images/e/e8/Bronzong.png', 'Steel', 'Bronze', 161, 213),
    ('Bonsly', 'https://static.wikia.nocookie.net/pokemongo/images/5/50/Bonsly.png', 'Rock', 'Bonsai', 124, 133),
    ('Mime Jr.', 'https://static.wikia.nocookie.net/pokemongo/images/b/b1/Mime_Jr..png', 'Psychic', 'Mime', 125, 142),
    ('Happiny', 'https://static.wikia.nocookie.net/pokemongo/images/d/d9/Happiny.png', 'Normal', 'Playhouse', 25, 77),
    ('Chatot', 'https://static.wikia.nocookie.net/pokemongo/images/1/17/Chatot.png', 'Normal', 'Music', 183, 91),
    ('Spiritomb', 'https://static.wikia.nocookie.net/pokemongo/images/f/fc/Spiritomb.png', 'Ghost', 'Forbidden', 169, 199),
    ('Gible', 'https://static.wikia.nocookie.net/pokemongo/images/3/37/Gible.png', 'Dragon', 'Land', 124, 84),
    ('Gabite', 'https://static.wikia.nocookie.net/pokemongo/images/f/f6/Gabite.png', 'Dragon', 'Cave', 172, 125),
    ('Garchomp', 'https://static.wikia.nocookie.net/pokemongo/images/e/e4/Garchomp.png', 'Dragon', 'Mach', 261, 193),
    ('Munchlax', 'https://static.wikia.nocookie.net/pokemongo/images/8/8e/Munchlax.png', 'Normal', 'Big', 137, 117),
    ('Riolu', 'https://static.wikia.nocookie.net/pokemongo/images/f/f0/Riolu.png', 'Fighting', 'Emanation', 127, 78),
    ('Lucario', 'https://static.wikia.nocookie.net/pokemongo/images/d/d0/Lucario.png', 'Fighting', 'Aura', 236, 144),
    ('Hippopotas', 'https://static.wikia.nocookie.net/pokemongo/images/9/96/Hippopotas.png', 'Ground', 'Hippo', 124, 118),
    ('Hippowdon', 'https://static.wikia.nocookie.net/pokemongo/images/9/9f/Hippowdon.png', 'Ground', 'Heavyweight', 201, 191),
    ('Skorupi', 'https://static.wikia.nocookie.net/pokemongo/images/3/3e/Skorupi.png', 'Poison', 'Scorpion', 93, 151),
    ('Drapion', 'https://static.wikia.nocookie.net/pokemongo/images/1/18/Drapion.png', 'Poison', 'Ogre', 180, 202),
    ('Croagunk', 'https://static.wikia.nocookie.net/pokemongo/images/1/1a/Croagunk.png', 'Poison', 'Toxic', 116, 76),
    ('Toxicroak', 'https://static.wikia.nocookie.net/pokemongo/images/1/1f/Toxicroak.png', 'Poison', 'Toxic', 211, 133),
    ('Carnivine', 'https://static.wikia.nocookie.net/pokemongo/images/f/f3/Carnivine.png', 'Grass', 'Bug', 187, 136),
    ('Finneon', 'https://static.wikia.nocookie.net/pokemongo/images/d/d3/Finneon.png', 'Water', 'Wing', 96, 116),
    ('Lumineon', 'https://static.wikia.nocookie.net/pokemongo/images/e/e9/Lumineon.png', 'Water', 'Neon', 142, 170),
    ('Mantyke', 'https://static.wikia.nocookie.net/pokemongo/images/6/69/Mantyke.png', 'Water', 'Kite', 105, 179),
    ('Snover', 'https://static.wikia.nocookie.net/pokemongo/images/0/09/Snover.png', 'Grass', 'Frost', 115, 105),
    ('Abomasnow', 'https://static.wikia.nocookie.net/pokemongo/images/b/b9/Abomasnow.png', 'Grass', 'Frost', 178, 158),
    ('Weavile', 'https://static.wikia.nocookie.net/pokemongo/images/5/57/Weavile.png', 'Dark', 'Sharp', 243, 171),
    ('Magnezone', 'https://static.wikia.nocookie.net/pokemongo/images/5/5a/Magnezone.png', 'Electric', 'Magnet', 238, 205),
    ('Lickilicky', 'https://static.wikia.nocookie.net/pokemongo/images/a/ab/Lickilicky.png', 'Normal', 'Licking', 161, 181),
    ('Rhyperior', 'https://static.wikia.nocookie.net/pokemongo/images/f/f1/Rhyperior.png', 'Ground', 'Drill', 241, 190),
    ('Tangrowth', 'https://static.wikia.nocookie.net/pokemongo/images/b/be/Tangrowth.png', 'Grass', 'Vine', 207, 184),
    ('Electivire', 'https://static.wikia.nocookie.net/pokemongo/images/e/ee/Electivire.png', 'Electric', 'Thunderbolt', 249, 163),
    ('Magmortar', 'https://static.wikia.nocookie.net/pokemongo/images/0/01/Magmortar.png', 'Fire', 'Blast', 247, 172),
    ('Togekiss', 'https://static.wikia.nocookie.net/pokemongo/images/7/7b/Togekiss.png', 'Fairy', 'Jubilee', 225, 217),
    ('Yanmega', 'https://static.wikia.nocookie.net/pokemongo/images/c/ca/Yanmega.png', 'Bug', 'Ogre', 231, 156),
    ('Leafeon', 'https://static.wikia.nocookie.net/pokemongo/images/9/91/Leafeon.png', 'Grass', 'Verdant', 216, 219),
    ('Glaceon', 'https://static.wikia.nocookie.net/pokemongo/images/f/fa/Glaceon.png', 'Ice', 'Fresh', 238, 205),
    ('Gliscor', 'https://static.wikia.nocookie.net/pokemongo/images/4/40/Gliscor.png', 'Ground', 'Fang', 185, 222),
    ('Mamoswine', 'https://static.wikia.nocookie.net/pokemongo/images/7/77/Mamoswine.png', 'Ice', 'Twin', 247, 146),
    ('Porygon-Z', 'https://static.wikia.nocookie.net/pokemongo/images/5/5d/Porygon-Z.png', 'Normal', 'Virtual', 264, 150),
    ('Gallade', 'https://static.wikia.nocookie.net/pokemongo/images/2/2d/Gallade.png', 'Psychic', 'Blade', 237, 195),
    ('Probopass', 'https://static.wikia.nocookie.net/pokemongo/images/6/64/Probopass.png', 'Rock', 'Compass', 135, 275),
    ('Dusknoir', 'https://static.wikia.nocookie.net/pokemongo/images/4/4b/Dusknoir.png', 'Ghost', 'Gripper', 180, 254),
    ('Froslass', 'https://static.wikia.nocookie.net/pokemongo/images/c/c3/Froslass.png', 'Ice', 'Snow', 171, 150),
    ('Rotom', 'https://static.wikia.nocookie.net/pokemongo/images/a/a5/Rotom.png', 'Electric', 'Plasma', 185, 159),
    ('Uxie', 'https://static.wikia.nocookie.net/pokemongo/images/e/e5/Uxie.png', 'Psychic', 'Knowledge', 156, 270),
    ('Mesprit', 'https://static.wikia.nocookie.net/pokemongo/images/c/c2/Mesprit.png', 'Psychic', 'Emotion', 212, 212),
    ('Azelf', 'https://static.wikia.nocookie.net/pokemongo/images/8/88/Azelf.png', 'Psychic', 'Willpower', 270, 151),
    ('Dialga', 'https://static.wikia.nocookie.net/pokemongo/images/4/4a/Dialga.png', 'Steel', 'Temporal', 275, 211),
    ('Palkia', 'https://static.wikia.nocookie.net/pokemongo/images/4/4f/Palkia.png', 'Water', 'Spatial', 280, 215),
    ('Heatran', 'https://static.wikia.nocookie.net/pokemongo/images/5/5c/Heatran.png', 'Fire', 'Lava', 251, 213),
    ('Regigigas', 'https://static.wikia.nocookie.net/pokemongo/images/1/19/Regigigas.png', 'Normal', 'Colossal', 287, 210),
    ('Giratina', 'https://static.wikia.nocookie.net/pokemongo/images/9/92/Giratina.png', 'Ghost', 'Renegade', 187, 225),
    ('Cresselia', 'https://static.wikia.nocookie.net/pokemongo/images/4/4a/Cresselia.png', 'Psychic', 'Lunar', 152, 258),
    ('Phione', 'https://static.wikia.nocookie.net/pokemongo/images/8/88/Phione.png', 'Water', 'Sea', 162, 162),
    ('Manaphy', 'https://static.wikia.nocookie.net/pokemongo/images/d/dd/Manaphy.png', 'Water', 'Seafaring', 210, 210),
    ('Darkrai', 'https://static.wikia.nocookie.net/pokemongo/images/5/50/Darkrai.png', 'Dark', 'Pitch-Black', 285, 198),
    ('Shaymin', 'https://static.wikia.nocookie.net/pokemongo/images/6/67/Shaymin.png', 'Grass', 'Gratitude', 210, 210),
    ('Arceus', 'https://static.wikia.nocookie.net/pokemongo/images/9/96/Arceus.png', 'Normal', 'Alpha', 238, 238),
    ('Victini', 'https://static.wikia.nocookie.net/pokemongo/images/4/45/Victini.png', 'Psychic', 'Victory', 210, 210),
    ('Snivy', 'https://static.wikia.nocookie.net/pokemongo/images/9/9a/Snivy.png', 'Grass', 'Grass', 88, 107),
    ('Servine', 'https://static.wikia.nocookie.net/pokemongo/images/f/fe/Servine.png', 'Grass', 'Grass', 122, 152),
    ('Serperior', 'https://static.wikia.nocookie.net/pokemongo/images/6/6a/Serperior.png', 'Grass', 'Regal', 161, 204),
    ('Tepig', 'https://static.wikia.nocookie.net/pokemongo/images/0/0e/Tepig.png', 'Fire', 'Fire', 115, 85),
    ('Pignite', 'https://static.wikia.nocookie.net/pokemongo/images/6/65/Pignite.png', 'Fire', 'Fire', 173, 106),
    ('Emboar', 'https://static.wikia.nocookie.net/pokemongo/images/1/15/Emboar.png', 'Fire', 'Mega', 235, 127),
    ('Oshawott', 'https://static.wikia.nocookie.net/pokemongo/images/e/e1/Oshawott.png', 'Water', 'Sea', 117, 85),
    ('Dewott', 'https://static.wikia.nocookie.net/pokemongo/images/b/b7/Dewott.png', 'Water', 'Discipline', 159, 116),
    ('Samurott', 'https://static.wikia.nocookie.net/pokemongo/images/d/d4/Samurott.png', 'Water', 'Formidable', 212, 157),
    ('Patrat', 'https://static.wikia.nocookie.net/pokemongo/images/5/58/Patrat.png', 'Normal', 'Scout', 98, 73),
    ('Watchog', 'https://static.wikia.nocookie.net/pokemongo/images/6/6d/Watchog.png', 'Normal', 'Lookout', 165, 139),
    ('Lillipup', 'https://static.wikia.nocookie.net/pokemongo/images/1/18/Lillipup.png', 'Normal', 'Puppy', 107, 86),
    ('Herdier', 'https://static.wikia.nocookie.net/pokemongo/images/4/4e/Herdier.png', 'Normal', 'Loyal', 145, 126),
    ('Stoutland', 'https://static.wikia.nocookie.net/pokemongo/images/8/8d/Stoutland.png', 'Normal', 'Big-Hearted', 206, 182);


USE PokemonDB;
INSERT INTO box (username, pokemonID)
VALUES
    ('alessandro.verdi', 324),
    ('alessandro.verdi', 56),
    ('alessandro.verdi', 198),
    ('alessandro.verdi', 127),
    ('alessandro.verdi', 432),
    ('alessandro.verdi', 19),
    ('alessandro.verdi', 275),
    ('alessandro.verdi', 88),
    ('alessandro.verdi', 5),
    ('alessandro.verdi', 341),
    ('alessandro.verdi', 67),
    ('alessandro.verdi', 415),
    ('alessandro.verdi', 152),
    ('alessandro.verdi', 299),
    ('alessandro.verdi', 174),
    ('alessandro.verdi', 422),
    ('alessandro.verdi', 235),
    ('alessandro.verdi', 189),
    ('alessandro.verdi', 67),
    ('alessandro.verdi', 123),
    ('elena.bianchi', 87),
    ('elena.bianchi', 245),
    ('elena.bianchi', 321),
    ('elena.bianchi', 42),
    ('elena.bianchi', 167),
    ('elena.bianchi', 408),
    ('elena.bianchi', 92),
    ('elena.bianchi', 175),
    ('elena.bianchi', 289),
    ('elena.bianchi', 53),
    ('elena.bianchi', 196),
    ('elena.bianchi', 374),
    ('elena.bianchi', 114),
    ('elena.bianchi', 299),
    ('elena.bianchi', 187),
    ('elena.bianchi', 432),
    ('elena.bianchi', 57),
    ('elena.bianchi', 341),
    ('elena.bianchi', 103),
    ('elena.bianchi', 219),
    ('andrea.rossi', 1),
    ('andrea.rossi', 2),
    ('andrea.rossi', 3),
    ('andrea.rossi', 4),
    ('andrea.rossi', 5),
    ('andrea.rossi', 6),
    ('andrea.rossi', 7),
    ('andrea.rossi', 8),
    ('andrea.rossi', 9),
    ('andrea.rossi', 10),
    ('andrea.rossi', 11),
    ('andrea.rossi', 12),
    ('andrea.rossi', 13),
    ('andrea.rossi', 14),
    ('andrea.rossi', 15),
    ('andrea.rossi', 16),
    ('andrea.rossi', 17),
    ('andrea.rossi', 18),
    ('ilaria.neri', 1),
    ('ilaria.neri', 2),
    ('ilaria.neri', 3),
    ('ilaria.neri', 4),
    ('ilaria.neri', 5),
    ('ilaria.neri', 6),
    ('ilaria.neri', 7),
    ('ilaria.neri', 8),
    ('ilaria.neri', 9),
    ('ilaria.neri', 10),
    ('ilaria.neri', 11),
    ('ilaria.neri', 12),
    ('ilaria.neri', 13),
    ('ilaria.neri', 14),
    ('ilaria.neri', 15),
    ('ilaria.neri', 16),
    ('ilaria.neri', 17),
    ('ilaria.neri', 18),
    ('ilaria.neri', 19),
    ('ilaria.neri', 20),
    ('maria.verdi',1),
    ('valentina.neri', ROUND(RAND() * 449) + 1),
    ('valentina.neri', ROUND(RAND() * 449) + 1),
    ('valentina.neri', ROUND(RAND() * 449) + 1),
    ('valentina.neri', ROUND(RAND() * 449) + 1),
    ('valentina.neri', ROUND(RAND() * 449) + 1),
    ('valentina.neri', ROUND(RAND() * 449) + 1),
    ('valentina.neri', ROUND(RAND() * 449) + 1),
    ('valentina.neri', ROUND(RAND() * 449) + 1),
    ('valentina.neri', ROUND(RAND() * 449) + 1),
    ('valentina.neri', ROUND(RAND() * 449) + 1),
    ('valentina.neri', ROUND(RAND() * 449) + 1),
    ('valentina.neri', ROUND(RAND() * 449) + 1),
    ('valentina.neri', ROUND(RAND() * 449) + 1),
    ('simone.rossi', ROUND(RAND() * 449) + 1),
    ('simone.rossi', ROUND(RAND() * 449) + 1),
    ('simone.rossi', ROUND(RAND() * 449) + 1),
    ('simone.rossi', ROUND(RAND() * 449) + 1),
    ('silvia.neri', ROUND(RAND() * 449) + 1),
    ('silvia.neri', ROUND(RAND() * 449) + 1),
    ('silvia.neri', ROUND(RAND() * 449) + 1),
    ('silvia.neri', ROUND(RAND() * 449) + 1),
    ('silvia.neri', ROUND(RAND() * 449) + 1),
    ('silvia.neri', ROUND(RAND() * 449) + 1),
    ('fabio.rossi', ROUND(RAND() * 449) + 1),
    ('fabio.rossi', ROUND(RAND() * 449) + 1),
    ('fabio.rossi', ROUND(RAND() * 449) + 1),
    ('fabio.rossi', ROUND(RAND() * 449) + 1),
    ('fabio.rossi', ROUND(RAND() * 449) + 1),
    ('francesca.bianchi', ROUND(RAND() * 449) + 1),
    ('francesca.bianchi', ROUND(RAND() * 449) + 1),
    ('francesca.bianchi', ROUND(RAND() * 449) + 1),
    ('francesca.bianchi', ROUND(RAND() * 449) + 1);


